# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a809cb573bca38033ddc795b75d31db273492632675ce2094c4fffaf7a05f2bde66c514c88e526686e98a9a9911c273c847dfed2249e89dc70dae918989c16

test:
  secret_key_base: 8ad19a5c37b4bba0d5c4e014c6ffa8e059e7e22d59da5e7ad150773401b721d6ea481dbaf405533efe07e43ddf893d38a4ffebed0fdf8b64d0a8dda0c2be24b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
